### ISSUE TITLE
Going "home" requires re-typing username and password

### ISSUE THREAD

**Issue by NoahMendoza** [AlyssaR/StudyNetwork#67]
If you are logged in and you hit the "home" button, the site maintains functionality but the text-boxes for entering your info re-appear, even though you never logged out.

**Comment by jrutz** [comment]
Additionally: You can also register a new account while you're still 'logged in' (if you go to the 'view account' from the home page without logging out, the last session's information is still there.

**Comment by AlyssaR** [comment]
This may be a GUI issue, @aakashpatel1 however I can do it, too. The problem is, as mentioned by @jrutz and @NoahMendoza the page does not check if the user has an active, logged in session before rendering the page. If this is done elements can be disabled for logged in users. 

Let me know if you'd prefer to do this, Kash, otherwise I will take care of this.

**Comment by AlyssaR** [comment]
Can no longer login without logging out. 

Still working on register issue.
