### ISSUE TITLE
Password Matching

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#70]
It works if you're doing it linearly (first then second), but it'll also tell you the password matches if the passwords initially matched - thought it won't let you make an account.
![screen shot 2015-04-13 at 11 04 35 am](https://cloud.githubusercontent.com/assets/5313865/7119855/b96204c6-e1ce-11e4-8d05-d0cae519164e.png)

**Comment by Ma1iciousL0af** [comment]
Fixed, but now the password matching colors show up when you first enter the password field, which could be annoying. Creating an i4 bugfix issue for this.

**Comment by Ma1iciousL0af** [comment]
Realized I forgot to ask for verification. @aakashpatel1 @KristoforHorst @AlyssaR, would one of you mind verifying?

**Comment by AlyssaR** [comment]
What branch did you fix this on, @aacarroll ?

**Comment by Ma1iciousL0af** [comment]
@AlyssaR Dev. Are the changes not showing? I might have not pushed everything by mistake

**Comment by AlyssaR** [comment]
@aacarroll The colors are right, unless I type in first, second, then change first. Then it shows they match because I think it only updates the check when the second field is altered.

**Comment by Ma1iciousL0af** [comment]
@AlyssaR Are you sure this isn't fixed? Just to make sure, I cloned dev somewhere else (to make sure there were no local changes), and the change I made seemed to stick, which fixes this.

**Comment by AlyssaR** [comment]
@aakashpatel1 @cknee217 @quincyschurr can someone else test this? It might be just me...

**Comment by quincyschurr** [comment]
@aacarroll - I tested this on dev. The box doesn't change color if you input the second field first however I do keep getting the popup error about how it can't contain characters when my passwords match up.

**Comment by Ma1iciousL0af** [comment]
@quincyschurr @AlyssaR I am very confused. This is what happens when I input into the second field first:
![untitled](https://cloud.githubusercontent.com/assets/5322497/7174464/71683b70-e3ce-11e4-85fc-b20817b0bc84.png)
And this is with entering a matching password in both boxes and then changing the first field. 
![untitled2](https://cloud.githubusercontent.com/assets/5322497/7174491/d4a4e4e0-e3ce-11e4-811f-09705d6f62aa.png)

Is this what y'all are seeing? Is there something I'm missing?

**Comment by quincyschurr** [comment]
@aacarroll No I get that too, but I also get a popup when I delete anything I've inputted all the way to the end or if I input the second field then the first and they match. Like this
![screen shot 2015-04-16 at 12 35 45 am](https://cloud.githubusercontent.com/assets/8551481/7174629/8de1846c-e3d0-11e4-8f0d-5d4a9b9e454f.png)

**Comment by AlyssaR** [comment]
@quincyschurr @aacarroll The popup is a separate error message. From my understanding the original error was that you could 
1) enter a password in field1
2) enter the same in field2
3) change the password in field1 and the color wouldn't change. 
-> So you'd get no error until you clicked register and got the popup. 

That was the error I was still getting. Can you verify that that's the actual problem @aacarroll ? If so can you repeat it with the steps I listed above?

**Comment by Ma1iciousL0af** [comment]
@AlyssaR Yes, that is the original issue. @quincyschurr The error message is popping up because the password in the fields is less than 8 characters. I repeated with the steps mentioned, and the color changes for me: 
![untitled3](https://cloud.githubusercontent.com/assets/5322497/7174758/40381b7a-e3d2-11e4-861a-91e6ba99bfaf.png)

**Comment by quincyschurr** [comment]
@aacarroll  then yes, this works correctly for me.

**Comment by quincyschurr** [comment]
So can this one be closed? I want to close things to make it look like we do work :)
