### ISSUE TITLE
The list of groups is not aligned with the column headings

### ISSUE THREAD

**Issue by williamoconnor** [AlyssaR/StudyNetwork#78]

**Comment by quincyschurr** [comment]
This looks like it will be fixed in the CSS integration. Is this a correct assumption @aacarroll @aakashpatel1

**Comment by Ma1iciousL0af** [comment]
Yes, that is correct :)

Sent from my iPhone

On Apr 20, 2015, at 2:11 PM, quincyschurr <notifications@github.com<mailto:notifications@github.com>> wrote:

This looks like it will be fixed in the CSS integration. Is this a correct assumption @aacarrollhttps://github.com/aacarroll @aakashpatel1https://github.com/aakashpatel1

##

**Comment by quincyschurr** [comment]
Cool! I can wait to close it then. Or one of you can close it if you feel like it's already integrated :)

**Comment by Ma1iciousL0af** [comment]
Fixed with bootstrap integration :)
